version: 0.1.0
name: mpg-inventory-managment
apiVersion: v1
description: Template configuration for a helm-based ArgoCD install. Copy this folder then update the values in requirements.yaml and values.yaml