dependencies:
- name: mpg-inventory-managment
  version: 5.0
  repository: 
https://artifactory-tools.cloudnativetoolkit-001-0e3e0ef4c9c6d831e8aa6fe01f33bfc4-0000.us-east.containers.appdomain.cloud/ui/packages